// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClientTerminalContextUpdatedNotification } from "./ClientTerminalContextUpdatedNotification";

export type ClientNotification = { "method": "initialized" } | { "method": "client/terminalContextUpdated", "params": ClientTerminalContextUpdatedNotification };
