// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClientTmuxContext } from "./ClientTmuxContext";

/**
 * Client terminal details that are not part of thread state, but can help the
 * app-server integrate spawned helper UI with the user's current terminal.
 */
export type ClientTerminalContext = { tmux?: ClientTmuxContext, };
